CREATE TABLE IF NOT EXISTS graphs (
    graph_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_guid uuid NOT NULL,
    graph_num integer NOT NULL,
    graph_data json NOT NULL
);


ALTER TABLE ONLY public.graphs
    ADD CONSTRAINT uni UNIQUE (user_guid, graph_num);